version: '3.4'

services:
    mssql:
        container_name: mssql
        environment:
            - SA_PASSWORD=MATF12345678rs2
            - ACCEPT_EULA=Y
        restart: always
        ports:
            - "1433:1433"
        volumes:
            - mssql_data:/var/opt/mssql/data

    identityserver:
        container_name: identityserver
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;"
        depends_on:
            - mssql
        ports:
            - "4000:80"
    userdb:
        container_name: userdb
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=UserDb
        restart: always
        ports:
        - "5432:5432"
        volumes:
        - postgres_data:/var/lib/postgresq
    pgadmin:
        container_name: pgadmin
        environment:
        - PGADMIN_DEFAULT_EMAIL=lakic.marija98@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=pgadmin
        restart: always
        ports:
        - "5050:80"
        volumes:
        - pgadmin_data:/root/.pgadmin

