version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile
  userdb:
    image: postgres  
  pgadmin:
    image: dpage/pgadmin4
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile
  conferencedb:
    image: postgres
  conference:
    image: ${DOCKER_REGISTRY-}conference
    build:
      context: .
      dockerfile: Services/Conference/Conference.Api/Dockerfile
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: SPAGateway/Dockerfile
  user.grpc:
    image: ${DOCKER_REGISTRY-}usergrpc
    build:
      context: .
      dockerfile: Services/User/User.GRPC/Dockerfile
  clamav:
    image: clamav/clamav
    extra_hosts:
      - "host.docker.internal:host-gateway"
  filedb:
    image: mongo:4.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
  file:
    image: ${DOCKER_REGISTRY-}file
    depends_on: 
      - filedb
      - clamav
    build:
      context: .
      dockerfile: Services/File/FileService/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  mssql_data:
  postgres_data_conference:
  postgres_data_user:
  pgadmin_data:
  clam_data:
  mongo_data:
