version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile
  userdb:
    image: postgres  
  pgadmin:
    image: dpage/pgadmin4
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Services/User/Dockerfile
  conferencedb:
    image: postgres
  conference:
    image: ${DOCKER_REGISTRY-}conference
    build:
      context: .
      dockerfile: Services/Conference/Conference.Api/Dockerfile
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: SPAGateway/Dockerfile
volumes:
  mssql_data:
  postgres_data_conference:
  postgres_data_user:
  pgadmin_data: