name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  lint-server:
    name: Lint check server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/ConSpaceServer/

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run linters on server app
        uses: wearerequired/lint-action@v1
        with:
          dotnet_format: true
          dotnet_format_dir: server/ConSpace

  lint-client:
    name: Lint check client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
          
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters on client app
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_dir: client