name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run linters on server app
        uses: wearerequired/lint-action@v1
        with:
          dotnet_format: true

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters on client app
        uses: wearerequired/lint-action@v1
        with:
          prettier: true